name: Build binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:20230110
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: make

      - name: Package
        run: |
          mkdir -p upload/apps/WADManager
          cp boot.dol upload/apps/WADManager
          cp boot.elf upload/apps/WADManager/WADManager_boot.elf
          cp WADManager/icon.png upload/apps/WADManager
          cp WADManager/meta.xml upload/apps/WADManager
          echo "sha=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: WADManager-${{ env.sha }}
          path: upload
